### ISSUE TITLE
Could not find Tunnels Exception

### ISSUE THREAD

**Issue by ksylvest** [jugyo/tunnels#1]
```
sudo tunnels
```

```
/Users/kevin/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find tunnels (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /Users/kevin/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
    from /Users/kevin/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems.rb:1208:in `gem'
    from /Users/kevin/.rvm/gems/ruby-1.9.3-p125/bin/tunnels:18:in `<main>'
```

**Comment by mataki** [comment]
me too!

**Comment by grimen** [comment]
+1

**Comment by mataki** [comment]
I shoud use `rvmsudo` command, to work with rvm.

```
rvmsudo tunnels
```

I can use tunnels by this command.

**Comment by mataki** [comment]
https://github.com/mataki/tunnels/commit/7c6d871f44944948db078d88155b868a430c2367

Pull request!

**Comment by jugyo** [comment]
+1

**Comment by jugyo** [comment]
The rvmsudo is nice.
I have fixed README as mataki's.

**Comment by rrooding** [comment]
rvmsudo doesn't fix it for me. I get this:

➜  ~  rvmsudo tunnels
env: tunnels: No such file or directory
